server:
  port: 8080
  servlet:
    context-path: "/codewr"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codewr_com
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

